### ISSUE TITLE
Exercise Screen

### ISSUE THREAD

**Issue by Cao1224** [AND102-FlexBody/FlexBody#13]
- [ ] Search for exercises
- [ ] Add exercise to list

**Comment by melissa-perez** [comment]
// TODO: add exercise fragment
        /*
        1. set up fragment here
        2. have search toolbar in action https://courses.codepath.org/courses/android_university_kotlin/unit/6#!exercises
        3. call api query
        4. create model for data
        5. create recyclerview to display api results
        6. no saving button yet

        7. if this works, nutrition is the same
         */
