### ISSUE TITLE
Configure API

### ISSUE THREAD

**Issue by Cao1224** [AND102-FlexBody/FlexBody#9]
Reference [API](https://wger.de/en/software/api)
- [x] Set up API call
- [x] Parse through JSON data and implement a RecyclerView to display
- [x] Use Glide to load and display images

**Comment by melissa-perez** [comment]
Done in Exercise Screen, Nutrition would be the same. Although the nutrition endpoint has no images and a bunch of data to display.

**Comment by melissa-perez** [comment]
Kind of done? Not sure about the nutrition screen.
